apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-file-search-data
  namespace: smart-file-search
  labels:
    app.kubernetes.io/name: smart-file-search
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
