# Logging configuration

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  
  json:
    format: "%(asctime)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    
  detailed:
    format: "%(asctime)s [%(levelname)s] %(name)s [%(filename)s:%(lineno)d] - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
    
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/smart-file-search.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 3

loggers:
  mcp_server:
    level: INFO
    handlers: [console, file]
    propagate: false
    
  search_agent:
    level: INFO
    handlers: [console, file]
    propagate: false
    
  llm:
    level: INFO
    handlers: [console, file] 
    propagate: false
    
  ui.backend:
    level: INFO
    handlers: [console, file]
    propagate: false
    
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false
    
  httpx:
    level: WARNING
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file]
